### ISSUE TITLE
Provide access to OembedResponse

### ISSUE THREAD

**Issue by george-007** [michael-simons/java-oembed#6]
Could the api of `OembedService ` provide access to `OembedResponse` ? 

It would be useful if the following method could be made public:
```java
Optional<OembedResponse> getOembedResponseFor(final String url)
```

We have used older version of java-oembed for fetching the height and width of youtube videos.
```java
OembedResponse response = oembed.transformUrl("http://www.youtube.com/watch?v=" + video.getId());
if (response != null) {
    video.setHeight(response.getHeight());
    video.setWidth(response.getWidth());
}
```
The dimensions are not available in youtube api v3:
https://code.google.com/p/gdata-issues/issues/detail?id=8090

**Comment by michael-simons** [comment]
0.5.6 should be in central maven the next hours. Let me know if this helps.

**Comment by george-007** [comment]
Thanks, version 0.5.5 fixed the issue.
